/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import static java.lang.Thread.sleep;
import java.sql.SQLException;

/**
 *
 * @author sunny
 */
public class AdminDashboard extends javax.swing.JFrame {
    Connection conn=null,connect=null,connSQLite=null;
    ResultSet rs=null,rs2=null;
    PreparedStatement pst=null,pst2=null;
    /**
     * Creates new form Dashboard
     */
    public void con(){
        connect=javaMySqlConnect.ConnectDB();
        if(connect == null){
            lblConnectionStatus.setText("OFFLINE");
            lblConnectionStatus.setForeground(Color.RED);
        }
        else{
            lblConnectionStatus.setText("ONLINE");
            lblConnectionStatus.setForeground(Color.GREEN);
        }        
    }
    public void getLogData(){
        String logUser="";
        try{
            String sql="Select * from user_log";
            pst2=connSQLite.prepareStatement(sql);
            rs2=pst2.executeQuery();
            while(rs2.next()){
                lblLoggedUser.setText(rs2.getString("log_empName"));
                lblAuthenticationType.setText(rs2.getString("log_authority"));
                logUser=rs2.getString("log_empName");
            }
            JOptionPane.showMessageDialog(null, "Welcome "+logUser,"Hello !",JOptionPane.PLAIN_MESSAGE);
            pst2.close();
        }
        catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e,"Exception in getLogData()",JOptionPane.ERROR_MESSAGE);
        }
    }
    public AdminDashboard() {
        initComponents();
        conn=javaMySqlConnect.ConnectDB();
        connSQLite=Connect.ConnectDB();
    }
    public void CurrentDate(){   
        Thread clock;
        clock = new Thread(){
            @Override
            public void run(){
                for(;;){
                    Calendar cal=new GregorianCalendar();
                    int month=cal.get(Calendar.MONTH);
                    int day=cal.get(Calendar.DAY_OF_MONTH);
                    int year=cal.get(Calendar.YEAR);
                    lblDate.setText("Date: "+day+"-"+month+"-"+year);

                    int second= cal.get(Calendar.SECOND);
                    int minute=cal.get(Calendar.MINUTE);
                    int hour=cal.get(Calendar.HOUR);
                    String AM_PM = cal.get(Calendar.AM_PM) == 0 ? "AM" : "PM";
                    lblTime.setText("Time: "+hour+":"+minute+":"+second+" "+AM_PM);   
                    try {
                        sleep(1000);
                    } 
                    catch (InterruptedException ex) {
                        //Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    con();
                }
            }
        };
        clock.start();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnDepartment = new javax.swing.JLabel();
        btnDoctor = new javax.swing.JLabel();
        btnPatient = new javax.swing.JLabel();
        btnNurse = new javax.swing.JLabel();
        btnPharmacist = new javax.swing.JLabel();
        btnLaboratorist = new javax.swing.JLabel();
        btnAccountant = new javax.swing.JLabel();
        btnAppointment = new javax.swing.JLabel();
        btnPayment = new javax.swing.JLabel();
        btnBloodBank = new javax.swing.JLabel();
        btnReport = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblHospitalManagerTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLoggedUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblConnectionStatus = new javax.swing.JLabel();
        lblAuthenticationType = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlHome = new javax.swing.JPanel();
        pnlCurrentPatient = new javax.swing.JPanel();
        pnlTodaysPatient = new javax.swing.JPanel();
        pnlRevenue = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAdmin = new javax.swing.JMenu();
        mnuManageAdministration = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuClose = new javax.swing.JMenuItem();
        mnuDepartment = new javax.swing.JMenu();
        mnuDoctor = new javax.swing.JMenu();
        mnuPatient = new javax.swing.JMenu();
        mnuNurse = new javax.swing.JMenu();
        mnuPharmacist = new javax.swing.JMenu();
        mnuLaboratorist = new javax.swing.JMenu();
        mnuAccountant = new javax.swing.JMenu();
        mnuAppointment = new javax.swing.JMenu();
        mnuPayment = new javax.swing.JMenu();
        mnuReport = new javax.swing.JMenu();
        mnuDashboards = new javax.swing.JMenu();
        mnuDoctorsDash = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuNursesDash = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuEmployeeDashboard = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuPharmacistDash = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuLaboratoristsDash = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenu();
        mnuAboutSoftware = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Manager - Dedicated towards healthcare");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(91, 77, 115));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(91, 77, 115));

        btnDepartment.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnDepartment.setForeground(java.awt.Color.white);
        btnDepartment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDepartment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hospitalDepartment_64.png"))); // NOI18N
        btnDepartment.setText("Department");
        btnDepartment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDepartment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepartmentMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDepartmentMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDepartmentMouseEntered(evt);
            }
        });

        btnDoctor.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnDoctor.setForeground(java.awt.Color.white);
        btnDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctor_64.png"))); // NOI18N
        btnDoctor.setText("Doctor");
        btnDoctor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoctor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoctorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoctorMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoctorMouseEntered(evt);
            }
        });

        btnPatient.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnPatient.setForeground(java.awt.Color.white);
        btnPatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Patients_64.png"))); // NOI18N
        btnPatient.setText("Patient");
        btnPatient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPatient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPatientMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPatientMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPatientMouseEntered(evt);
            }
        });

        btnNurse.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnNurse.setForeground(java.awt.Color.white);
        btnNurse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNurse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nurse_64.png"))); // NOI18N
        btnNurse.setText("Nurse");
        btnNurse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNurse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNurse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNurseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNurseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNurseMouseEntered(evt);
            }
        });

        btnPharmacist.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnPharmacist.setForeground(java.awt.Color.white);
        btnPharmacist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPharmacist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pharmacy.png"))); // NOI18N
        btnPharmacist.setText("Pharmacist");
        btnPharmacist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPharmacist.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPharmacist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPharmacistMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPharmacistMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPharmacistMouseEntered(evt);
            }
        });

        btnLaboratorist.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnLaboratorist.setForeground(java.awt.Color.white);
        btnLaboratorist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLaboratorist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/laboratorist_64.png"))); // NOI18N
        btnLaboratorist.setText("Laboratorist");
        btnLaboratorist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLaboratorist.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLaboratorist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaboratoristMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaboratoristMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaboratoristMouseEntered(evt);
            }
        });

        btnAccountant.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnAccountant.setForeground(java.awt.Color.white);
        btnAccountant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAccountant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accountant_64.png"))); // NOI18N
        btnAccountant.setText("Accountant");
        btnAccountant.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccountant.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccountant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAccountantMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccountantMouseEntered(evt);
            }
        });

        btnAppointment.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnAppointment.setForeground(java.awt.Color.white);
        btnAppointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/appointment_64.png"))); // NOI18N
        btnAppointment.setText("Appointment");
        btnAppointment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAppointment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAppointmentMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAppointmentMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAppointmentMouseEntered(evt);
            }
        });

        btnPayment.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnPayment.setForeground(java.awt.Color.white);
        btnPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payment.png"))); // NOI18N
        btnPayment.setText("Payment");
        btnPayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPayment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPaymentMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPaymentMouseEntered(evt);
            }
        });

        btnBloodBank.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnBloodBank.setForeground(java.awt.Color.white);
        btnBloodBank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBloodBank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blood-drop_64.png"))); // NOI18N
        btnBloodBank.setText("Blood Bank");
        btnBloodBank.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBloodBank.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBloodBank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBloodBankMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBloodBankMouseEntered(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnReport.setForeground(java.awt.Color.white);
        btnReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report_64.png"))); // NOI18N
        btnReport.setText("Report");
        btnReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnHome.setForeground(java.awt.Color.white);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_64.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPharmacist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAccountant, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNurse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLaboratorist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBloodBank, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnPayment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDoctor)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNurse)
                            .addComponent(btnPatient))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPharmacist)
                    .addComponent(btnLaboratorist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccountant)
                    .addComponent(btnAppointment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPayment)
                    .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBloodBank)
                    .addComponent(btnDepartment))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 83, -1, -1));

        jPanel3.setBackground(new java.awt.Color(91, 77, 115));

        lblHospitalManagerTitle.setBackground(java.awt.Color.white);
        lblHospitalManagerTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HospitalManagerDash.png"))); // NOI18N
        lblHospitalManagerTitle.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Active Login:");

        lblLoggedUser.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblLoggedUser.setForeground(new java.awt.Color(0, 210, 255));
        lblLoggedUser.setText("Logged User");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Connection Status:");

        lblConnectionStatus.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblConnectionStatus.setForeground(new java.awt.Color(209, 1, 1));
        lblConnectionStatus.setText("OFFLINE");

        lblAuthenticationType.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblAuthenticationType.setForeground(new java.awt.Color(0, 210, 255));
        lblAuthenticationType.setText("Authority");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Authentication Type:");

        lblDate.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDate.setForeground(new java.awt.Color(254, 254, 254));
        lblDate.setText("DATE");

        lblTime.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblTime.setForeground(new java.awt.Color(254, 254, 254));
        lblTime.setText("TIME");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHospitalManagerTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConnectionStatus)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLoggedUser)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAuthenticationType)
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblHospitalManagerTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblConnectionStatus)
                            .addComponent(jLabel1)
                            .addComponent(lblLoggedUser)
                            .addComponent(jLabel3)
                            .addComponent(lblAuthenticationType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTime))))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1355, -1));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlHome.setBackground(new java.awt.Color(91, 77, 115));
        pnlHome.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "HOSPITAL STATUS MONITOR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 14), java.awt.Color.white)); // NOI18N
        pnlHome.setForeground(java.awt.Color.white);

        pnlCurrentPatient.setBackground(new java.awt.Color(91, 77, 115));
        pnlCurrentPatient.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Current Admission's", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), java.awt.Color.white)); // NOI18N

        javax.swing.GroupLayout pnlCurrentPatientLayout = new javax.swing.GroupLayout(pnlCurrentPatient);
        pnlCurrentPatient.setLayout(pnlCurrentPatientLayout);
        pnlCurrentPatientLayout.setHorizontalGroup(
            pnlCurrentPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        pnlCurrentPatientLayout.setVerticalGroup(
            pnlCurrentPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlTodaysPatient.setBackground(new java.awt.Color(91, 77, 115));
        pnlTodaysPatient.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Current Admission's", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), java.awt.Color.white)); // NOI18N

        javax.swing.GroupLayout pnlTodaysPatientLayout = new javax.swing.GroupLayout(pnlTodaysPatient);
        pnlTodaysPatient.setLayout(pnlTodaysPatientLayout);
        pnlTodaysPatientLayout.setHorizontalGroup(
            pnlTodaysPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        pnlTodaysPatientLayout.setVerticalGroup(
            pnlTodaysPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        pnlRevenue.setBackground(new java.awt.Color(91, 77, 115));
        pnlRevenue.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Current Admission's", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), java.awt.Color.white)); // NOI18N

        javax.swing.GroupLayout pnlRevenueLayout = new javax.swing.GroupLayout(pnlRevenue);
        pnlRevenue.setLayout(pnlRevenueLayout);
        pnlRevenueLayout.setHorizontalGroup(
            pnlRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlRevenueLayout.setVerticalGroup(
            pnlRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addComponent(pnlCurrentPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTodaysPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTodaysPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCurrentPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(pnlHome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 83, -1, 644));

        jMenuBar1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        mnuAdmin.setText("Admin");

        mnuManageAdministration.setText("Manage Users");
        mnuManageAdministration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageAdministrationActionPerformed(evt);
            }
        });
        mnuAdmin.add(mnuManageAdministration);
        mnuAdmin.add(jSeparator6);

        mnuClose.setText("Close");
        mnuClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCloseMouseClicked(evt);
            }
        });
        mnuAdmin.add(mnuClose);

        jMenuBar1.add(mnuAdmin);

        mnuDepartment.setText("Department");
        mnuDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuDepartmentMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuDepartment);

        mnuDoctor.setText("Doctor");
        mnuDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuDoctorMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuDoctor);

        mnuPatient.setText("Patient");
        mnuPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuPatientMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuPatient);

        mnuNurse.setText("Nurse");
        mnuNurse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuNurseMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuNurse);

        mnuPharmacist.setText("Pharmacist");
        mnuPharmacist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuPharmacistMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuPharmacist);

        mnuLaboratorist.setText("Laboratorist");
        mnuLaboratorist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuLaboratoristMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuLaboratorist);

        mnuAccountant.setText("Accountant");
        mnuAccountant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAccountantMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuAccountant);

        mnuAppointment.setText("Appointment");
        mnuAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAppointmentMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuAppointment);

        mnuPayment.setText("Payment");
        mnuPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuPaymentMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuPayment);

        mnuReport.setText("Report");
        mnuReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuReportMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuReport);

        mnuDashboards.setText("Dashboards");

        mnuDoctorsDash.setText("Doctor Dashboard");
        mnuDoctorsDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuDoctorsDashMousePressed(evt);
            }
        });
        mnuDoctorsDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoctorsDashActionPerformed(evt);
            }
        });
        mnuDashboards.add(mnuDoctorsDash);
        mnuDashboards.add(jSeparator1);

        mnuNursesDash.setText("Staff Dashboard");
        mnuNursesDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuNursesDashMousePressed(evt);
            }
        });
        mnuNursesDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNursesDashActionPerformed(evt);
            }
        });
        mnuDashboards.add(mnuNursesDash);
        mnuDashboards.add(jSeparator2);

        mnuEmployeeDashboard.setText("Employee Dashboard");
        mnuEmployeeDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmployeeDashboardActionPerformed(evt);
            }
        });
        mnuDashboards.add(mnuEmployeeDashboard);
        mnuDashboards.add(jSeparator3);

        mnuPharmacistDash.setText("Pharmacy Dashboard");
        mnuPharmacistDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuPharmacistDashMousePressed(evt);
            }
        });
        mnuPharmacistDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPharmacistDashActionPerformed(evt);
            }
        });
        mnuDashboards.add(mnuPharmacistDash);
        mnuDashboards.add(jSeparator5);

        mnuLaboratoristsDash.setText("Laboratory Dashboard");
        mnuLaboratoristsDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuLaboratoristsDashMousePressed(evt);
            }
        });
        mnuDashboards.add(mnuLaboratoristsDash);

        jMenuBar1.add(mnuDashboards);

        mnuAbout.setText("About");

        mnuAboutSoftware.setText("About Hospital Manager");
        mnuAbout.add(mnuAboutSoftware);

        jMenuItem1.setText("About Developer");
        mnuAbout.add(jMenuItem1);

        jMenuBar1.add(mnuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1365, 790));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        CurrentDate();
        getLogData();
    }//GEN-LAST:event_formWindowOpened

    private void btnDepartmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartmentMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/hospitalDepartment_hover_64.png"));
        btnDepartment.setIcon(II);
    }//GEN-LAST:event_btnDepartmentMouseEntered

    private void btnDepartmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartmentMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/hospitalDepartment_64.png"));
        btnDepartment.setIcon(II);
    }//GEN-LAST:event_btnDepartmentMouseExited

    private void btnDoctorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/doctor_hover_64.png"));
        btnDoctor.setIcon(II);
    }//GEN-LAST:event_btnDoctorMouseEntered

    private void btnDoctorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/doctor_64.png"));
        btnDoctor.setIcon(II);
    }//GEN-LAST:event_btnDoctorMouseExited

    private void btnPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatientMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/Patients_hover_64.png"));
        btnPatient.setIcon(II);
    }//GEN-LAST:event_btnPatientMouseEntered

    private void btnPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatientMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/Patients_64.png"));
        btnPatient.setIcon(II);
    }//GEN-LAST:event_btnPatientMouseExited

    private void btnNurseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNurseMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/nurse_hover_64.png"));
        btnNurse.setIcon(II);
    }//GEN-LAST:event_btnNurseMouseEntered

    private void btnNurseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNurseMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/nurse_64.png"));
        btnNurse.setIcon(II);
    }//GEN-LAST:event_btnNurseMouseExited

    private void btnPharmacistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPharmacistMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/pharmacy_hover.png"));
        btnPharmacist.setIcon(II);
    }//GEN-LAST:event_btnPharmacistMouseEntered

    private void btnPharmacistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPharmacistMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/pharmacy.png"));
        btnPharmacist.setIcon(II);
    }//GEN-LAST:event_btnPharmacistMouseExited

    private void btnLaboratoristMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratoristMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/laboratorist_hover_64.png"));
        btnLaboratorist.setIcon(II);
    }//GEN-LAST:event_btnLaboratoristMouseEntered

    private void btnLaboratoristMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratoristMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/laboratorist_64.png"));
        btnLaboratorist.setIcon(II);
    }//GEN-LAST:event_btnLaboratoristMouseExited

    private void btnAccountantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccountantMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/accountant_hover_64.png"));
        btnAccountant.setIcon(II);
    }//GEN-LAST:event_btnAccountantMouseEntered

    private void btnAccountantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccountantMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/accountant_64.png"));
        btnAccountant.setIcon(II);
    }//GEN-LAST:event_btnAccountantMouseExited

    private void btnAppointmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointmentMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/appointment_hover_64.png"));
        btnAppointment.setIcon(II);
    }//GEN-LAST:event_btnAppointmentMouseEntered

    private void btnAppointmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointmentMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/appointment_64.png"));
        btnAppointment.setIcon(II);
    }//GEN-LAST:event_btnAppointmentMouseExited

    private void btnPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/payment_hover.png"));
        btnPayment.setIcon(II);
    }//GEN-LAST:event_btnPaymentMouseEntered

    private void btnPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/payment.png"));
        btnPayment.setIcon(II);
    }//GEN-LAST:event_btnPaymentMouseExited

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/report_hover_64.png"));
        btnReport.setIcon(II);
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/report_64.png"));
        btnReport.setIcon(II);
    }//GEN-LAST:event_btnReportMouseExited

    private void btnPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatientMouseClicked
        // TODO add your handling code here:
       PatientDepartments.getObj().setVisible(true);
    }//GEN-LAST:event_btnPatientMouseClicked

    private void btnDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartmentMouseClicked
        // TODO add your handling code here:
        Department.getObj().setVisible(true);
    }//GEN-LAST:event_btnDepartmentMouseClicked

    private void btnDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorMouseClicked
        // TODO add your handling code here:
        Doctor.getObj().setVisible(true);
    }//GEN-LAST:event_btnDoctorMouseClicked

    private void btnNurseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNurseMouseClicked
        // TODO add your handling code here:
        Nurse nurse=new Nurse();
        nurse.setVisible(true);
    }//GEN-LAST:event_btnNurseMouseClicked

    private void btnLaboratoristMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratoristMouseClicked
        // TODO add your handling code here:
        Laboratorist lab=new Laboratorist();
        lab.setVisible(true);
    }//GEN-LAST:event_btnLaboratoristMouseClicked

    private void btnPharmacistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPharmacistMouseClicked
        // TODO add your handling code here:
        Pharmacist phar=new Pharmacist();
        phar.setVisible(true);
    }//GEN-LAST:event_btnPharmacistMouseClicked

    private void btnAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointmentMouseClicked
        // TODO add your handling code here:
        Appointment apoint=new Appointment();
        apoint.setVisible(true);
    }//GEN-LAST:event_btnAppointmentMouseClicked

    private void mnuDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDepartmentMouseClicked
        // TODO add your handling code here:
        Department dept=new Department();
        dept.setVisible(true);
    }//GEN-LAST:event_mnuDepartmentMouseClicked

    private void mnuDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDoctorMouseClicked
        // TODO add your handling code here:
        Doctor doc=new Doctor();
        doc.setVisible(true);
    }//GEN-LAST:event_mnuDoctorMouseClicked

    private void mnuPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuPatientMouseClicked
        // TODO add your handling code here:
        PatientDepartments pat=new PatientDepartments();
        pat.setVisible(true);
    }//GEN-LAST:event_mnuPatientMouseClicked

    private void mnuNurseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuNurseMouseClicked
        // TODO add your handling code here:
        Nurse nur=new Nurse();
        nur.setVisible(true);
    }//GEN-LAST:event_mnuNurseMouseClicked

    private void mnuPharmacistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuPharmacistMouseClicked
        // TODO add your handling code here:
        Pharmacist phar=new Pharmacist();
        phar.setVisible(true);
    }//GEN-LAST:event_mnuPharmacistMouseClicked

    private void mnuLaboratoristMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuLaboratoristMouseClicked
        // TODO add your handling code here:
        Laboratorist lab=new Laboratorist();
        lab.setVisible(true);
    }//GEN-LAST:event_mnuLaboratoristMouseClicked

    private void mnuAccountantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAccountantMouseClicked
        // TODO add your handling code here:
        Accountant acc=new Accountant();
        acc.setVisible(true);
    }//GEN-LAST:event_mnuAccountantMouseClicked

    private void mnuAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAppointmentMouseClicked
        // TODO add your handling code here:
        Appointment app=new Appointment();
        app.setVisible(true);
    }//GEN-LAST:event_mnuAppointmentMouseClicked

    private void mnuPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuPaymentMouseClicked
        // TODO add your handling code here:
        Payment pmt=new Payment();
        pmt.setVisible(true);
    }//GEN-LAST:event_mnuPaymentMouseClicked

    private void mnuReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuReportMouseClicked
        // TODO add your handling code here:
        Report rpt=new Report();
        rpt.setVisible(true);
    }//GEN-LAST:event_mnuReportMouseClicked

    private void btnBloodBankMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBloodBankMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/blood-drop_hover_64.png"));
        btnBloodBank.setIcon(II);
    }//GEN-LAST:event_btnBloodBankMouseEntered

    private void btnBloodBankMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBloodBankMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/blood-drop_64.png"));
        btnBloodBank.setIcon(II);
    }//GEN-LAST:event_btnBloodBankMouseExited

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/home_64.png"));
        btnHome.setIcon(II);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/images/home_hover_64.png"));
        btnHome.setIcon(II);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void mnuDoctorsDashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDoctorsDashMousePressed
        // TODO add your handling code here:
        DoctorDashboard docDash=new DoctorDashboard();
        docDash.setVisible(true);
    }//GEN-LAST:event_mnuDoctorsDashMousePressed

    private void mnuNursesDashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuNursesDashMousePressed
        // TODO add your handling code here:
        StaffDashboard NurseDash=new StaffDashboard();
        NurseDash.setVisible(true);
    }//GEN-LAST:event_mnuNursesDashMousePressed

    private void mnuPharmacistDashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuPharmacistDashMousePressed
        // TODO add your handling code here:
        PharmacistDashboard pharmaDash=new PharmacistDashboard();
        pharmaDash.setVisible(true);
    }//GEN-LAST:event_mnuPharmacistDashMousePressed

    private void mnuLaboratoristsDashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuLaboratoristsDashMousePressed
        // TODO add your handling code here:
        LaboratoristDashboard labDash=new LaboratoristDashboard();
        labDash.setVisible(true);
    }//GEN-LAST:event_mnuLaboratoristsDashMousePressed

    private void mnuCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCloseMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuCloseMouseClicked
    
    private void mnuManageAdministrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageAdministrationActionPerformed
        // TODO add your handling code here:
        ManageUsers mu=new ManageUsers();
        mu.setVisible(true);
    }//GEN-LAST:event_mnuManageAdministrationActionPerformed

    private void mnuEmployeeDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmployeeDashboardActionPerformed
        // TODO add your handling code here:
        EmployeeDashboard empDash=new EmployeeDashboard();
        empDash.setVisible(true);
    }//GEN-LAST:event_mnuEmployeeDashboardActionPerformed

    private void mnuNursesDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNursesDashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuNursesDashActionPerformed

    private void mnuDoctorsDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoctorsDashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuDoctorsDashActionPerformed

    private void mnuPharmacistDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPharmacistDashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuPharmacistDashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAccountant;
    private javax.swing.JLabel btnAppointment;
    private javax.swing.JLabel btnBloodBank;
    private javax.swing.JLabel btnDepartment;
    private javax.swing.JLabel btnDoctor;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLaboratorist;
    private javax.swing.JLabel btnNurse;
    private javax.swing.JLabel btnPatient;
    private javax.swing.JLabel btnPayment;
    private javax.swing.JLabel btnPharmacist;
    private javax.swing.JLabel btnReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel lblAuthenticationType;
    private javax.swing.JLabel lblConnectionStatus;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHospitalManagerTitle;
    private javax.swing.JLabel lblLoggedUser;
    private javax.swing.JLabel lblTime;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenuItem mnuAboutSoftware;
    private javax.swing.JMenu mnuAccountant;
    private javax.swing.JMenu mnuAdmin;
    private javax.swing.JMenu mnuAppointment;
    private javax.swing.JMenuItem mnuClose;
    private javax.swing.JMenu mnuDashboards;
    private javax.swing.JMenu mnuDepartment;
    private javax.swing.JMenu mnuDoctor;
    private javax.swing.JMenuItem mnuDoctorsDash;
    private javax.swing.JMenuItem mnuEmployeeDashboard;
    private javax.swing.JMenu mnuLaboratorist;
    private javax.swing.JMenuItem mnuLaboratoristsDash;
    private javax.swing.JMenuItem mnuManageAdministration;
    private javax.swing.JMenu mnuNurse;
    private javax.swing.JMenuItem mnuNursesDash;
    private javax.swing.JMenu mnuPatient;
    private javax.swing.JMenu mnuPayment;
    private javax.swing.JMenu mnuPharmacist;
    private javax.swing.JMenuItem mnuPharmacistDash;
    private javax.swing.JMenu mnuReport;
    private javax.swing.JPanel pnlCurrentPatient;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlRevenue;
    private javax.swing.JPanel pnlTodaysPatient;
    // End of variables declaration//GEN-END:variables
}
