/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import javax.swing.JFrame;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import static java.lang.Thread.sleep;
import java.sql.SQLException;

/**
 *
 * @author sunny
 */
public class EmployeeDashboard extends javax.swing.JFrame {

    Connection conn=null,connect=null,connSQLite=null;
    ResultSet rs=null,rs2=null;
    PreparedStatement pst=null,pst2=null;
    /**
     * Creates new form EmployeeDashboard
     */
    public void con(){
        connect=javaMySqlConnect.ConnectDB();
        if(connect == null){
            lblConnectionStatus.setText("OFFLINE");
            lblConnectionStatus.setForeground(Color.RED);
        }
        else{
            lblConnectionStatus.setText("ONLINE");
            lblConnectionStatus.setForeground(Color.GREEN);
        }        
    }
    public EmployeeDashboard() {
        initComponents();
        conn=javaMySqlConnect.ConnectDB();
        connSQLite=Connect.ConnectDB();
    }
    public void CurrentDate(){   
        Thread clock;
        clock = new Thread(){
            @Override
            public void run(){
                for(;;){
                    Calendar cal=new GregorianCalendar();
                    int month=cal.get(Calendar.MONTH);
                    int day=cal.get(Calendar.DAY_OF_MONTH);
                    int year=cal.get(Calendar.YEAR);
                    lblDate.setText("Date: "+day+"-"+month+"-"+year);

                    int second= cal.get(Calendar.SECOND);
                    int minute=cal.get(Calendar.MINUTE);
                    int hour=cal.get(Calendar.HOUR);
                    String AM_PM = cal.get(Calendar.AM_PM) == 0 ? "AM" : "PM";
                    lblTime.setText("Time: "+hour+":"+minute+":"+second+" "+AM_PM);   
                    try {
                        sleep(1000);
                    } 
                    catch (InterruptedException ex) {
                        //Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    con();
                }
            }
        };
        clock.start();  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblConnectionStatus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLoggedUser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAuthenticationType = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee DashBoard - Hospital Manager");
        setBackground(new java.awt.Color(82, 25, 155));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(91, 77, 115));
        jPanel3.setForeground(java.awt.Color.white);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employeeDashboard.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HospitalManagerDash.png"))); // NOI18N
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 330, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Connection Status:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, -1, -1));

        lblConnectionStatus.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblConnectionStatus.setForeground(new java.awt.Color(209, 1, 1));
        lblConnectionStatus.setText("OFFLINE");
        jPanel3.add(lblConnectionStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Active Login:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, -1));

        lblLoggedUser.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblLoggedUser.setForeground(new java.awt.Color(0, 210, 255));
        lblLoggedUser.setText("Logged User");
        jPanel3.add(lblLoggedUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Authentication Type:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, -1, -1));

        lblAuthenticationType.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblAuthenticationType.setForeground(new java.awt.Color(0, 210, 255));
        lblAuthenticationType.setText("Authority");
        jPanel3.add(lblAuthenticationType, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, -1, -1));

        lblDate.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDate.setForeground(new java.awt.Color(254, 254, 254));
        lblDate.setText("DATE");
        jPanel3.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 160, -1));

        lblTime.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblTime.setForeground(new java.awt.Color(254, 254, 254));
        lblTime.setText("TIME");
        jPanel3.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 60, 160, -1));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1310, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAuthenticationType;
    private javax.swing.JLabel lblConnectionStatus;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLoggedUser;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
