/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.HeadlessException;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import javax.swing.*;
import javax.xml.soap.SOAPBody;
import net.proteanit.sql.DbUtils;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author sunny
 */
public class OPDBilling extends javax.swing.JFrame {
    String patientID;
    String patientName;
    Connection conn=null,conn2=null,conn10=null,connSQLite=null;
    PreparedStatement pst=null,pst2=null,pst10=null;
    ResultSet rs=null,rs2=null,rs10=null;
    /**
     * Creates new form OPDReciept
     * 
     */
    public OPDBilling() {        
        initComponents();
        conn=javaMySqlConnect.ConnectDB();
        conn2=javaMySqlConnect.ConnectDB();
        conn10=javaMySqlConnect.ConnectDB();
        connSQLite=Connect.ConnectDB();        
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtServiceDesc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServiceDesc = new javax.swing.JTable();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOPDDiagnosticsAndTests = new javax.swing.JTable();
        lblClose = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbPaymentType = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtPaymentDescription = new javax.swing.JTextField();
        txtGrandTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnUpdtBilling = new javax.swing.JButton();
        btnPrintBilling = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtOverAllTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTax = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBillNumber = new javax.swing.JTextField();
        btnSaveBilling = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OPD BILLING-Hospital Manager");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(91, 77, 115));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(235, 233, 233)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(91, 77, 115));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), java.awt.Color.white)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Patient ID");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Patient Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPatientName, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1000, 70));

        jPanel3.setBackground(new java.awt.Color(91, 77, 115));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Service Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), java.awt.Color.white)); // NOI18N
        jPanel3.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Service Description");

        txtTotal.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cost");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Qty");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total");

        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtServiceDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtServiceDescKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtServiceDescKeyReleased(evt);
            }
        });

        tblServiceDesc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblServiceDesc);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                            .addComponent(txtServiceDesc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCost)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQty)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addGap(331, 331, 331))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnDelete, btnUpdate});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServiceDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1000, 180));

        lblDate.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblDate.setForeground(java.awt.Color.white);
        lblDate.setText("DATE");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 120, 20));

        lblTime.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblTime.setForeground(java.awt.Color.white);
        lblTime.setText("TIME");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 130, 20));

        tblOPDDiagnosticsAndTests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblOPDDiagnosticsAndTests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOPDDiagnosticsAndTestsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOPDDiagnosticsAndTests);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 1000, 210));

        lblClose.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 0, 0));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setToolTipText("Click here to close this Window");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 30, 20));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("OPD Services Billing");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 290, -1));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Payment Type");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 100, 20));

        cmbPaymentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Cheque" }));
        jPanel1.add(cmbPaymentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 410, -1));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Description");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 90, 20));
        jPanel1.add(txtPaymentDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 410, -1));
        jPanel1.add(txtGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 560, 100, -1));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("GRAND TOTAL");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 100, 20));

        btnUpdtBilling.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnUpdtBilling.setText("Update Billng");
        btnUpdtBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdtBillingActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdtBilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 140, -1));

        btnPrintBilling.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnPrintBilling.setText("PRINT");
        jPanel1.add(btnPrintBilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 70, -1));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Overall Total");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 100, 20));
        jPanel1.add(txtOverAllTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 100, -1));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tax");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 100, 20));

        txtTax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTaxKeyReleased(evt);
            }
        });
        jPanel1.add(txtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 100, -1));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Bill Number :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, 30));

        txtBillNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBillNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBillNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 190, 30));

        btnSaveBilling.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnSaveBilling.setText("SAVE");
        btnSaveBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBillingActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveBilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1020, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked
    //Program to display Date and Time
    String dt,tm;
    public void CurrentDate(){   
        Thread clock;
        clock = new Thread(){
            @Override
            public void run(){
                for(;;){
                    Calendar cal=new GregorianCalendar();
                    int month=cal.get(Calendar.MONTH);
                    int day=cal.get(Calendar.DAY_OF_MONTH);
                    int year=cal.get(Calendar.YEAR);
                    dt=year+"-"+month+"-"+day;
                    lblDate.setText("Date: "+day+"-"+month+"-"+year);

                    int second= cal.get(Calendar.SECOND);
                    int minute=cal.get(Calendar.MINUTE);
                    int hour=cal.get(Calendar.HOUR);
                    String AM_PM = cal.get(Calendar.AM_PM) == 0 ? "AM" : "PM";
                    tm=hour+":"+minute+":"+second;
                    lblTime.setText("Time: "+hour+":"+minute+":"+second+" "+AM_PM);
                    try {
                        sleep(1000);
                    } 
                    catch (InterruptedException ex) {
                        //Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        clock.start();  
    }
    //Program to get current_opd_patient
    public void getCurrentOPDPat(){
        try{
            String sql="Select * from current_opd_patient";
            pst=connSQLite.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                txtPatientID.setText(rs.getString("opd_id"));
                txtPatientName.setText(rs.getString("opd_patName"));
            }
            pst.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //Program to get Bill Count and Content Count
    public void getBillNumber(){
        int billNo=0;
        try{
            String sql="Select * from opdbilling";
            pst=conn.prepareStatement(sql);       
            rs=pst.executeQuery();
            while(rs.next()){
                billNo=rs.getInt("bill_no");
            }
            billNo++;
            txtBillNumber.setText(String.valueOf(billNo));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        txtServiceDesc.requestFocus();
    }
    //Program to get active user from hmdb_local
    String opdActiveUsername;
    public void getActiveUser(){
        try{
            String sql="Select * from user_log";
            pst=connSQLite.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                opdActiveUsername=rs.getString("log_empName");
            }
            pst.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        CurrentDate();
        getActiveUser();
        getCurrentOPDPat();
        getBillNumber();
    }//GEN-LAST:event_formWindowOpened
    
    //Program to perform calculation
    double tot=0,price=0,tax=0,gt=0,taxper=0;
    public void totalCalc(){
        try{
            String sql="Select * from opdbillingcontent where opdBillNumber='"+txtBillNumber.getText()+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                price=rs.getDouble("opdServiceTotalCost");
                tot=tot+price;
                txtOverAllTotal.setText(String.valueOf(tot));
                tax=tot*(taxper/100);
                gt=tot+tax;
                txtGrandTotal.setText(String.valueOf(gt));
            }
            pst.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e,"addCalculation() Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    //Program to clear service fields and set focus to Service Description field
    public void clearfield(){
        txtServiceDesc.setText("");
        txtCost.setText("");
        txtQty.setText("");
        txtTotal.setText("");
        txtServiceDesc.requestFocus();
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addProduct();
        totalCalc();
        readBillData();
        clearfield();
    }//GEN-LAST:event_btnAddActionPerformed
    //Program to get data from Service Description Table
    public void getServiceData(){
        try{            
            String KeyVal=txtServiceDesc.getText();
            String sql4="Select * from diagnosticsandtests where Service_Name LIKE ?";
            pst10=conn10.prepareStatement(sql4);
            pst10.setString(1,"%"+KeyVal + "%");
            rs10=pst10.executeQuery();
            tblServiceDesc.setModel(DbUtils.resultSetToTableModel(rs10));
            pst10.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e,"getServiceData() Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void txtServiceDescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServiceDescKeyReleased
        getServiceData();        
    }//GEN-LAST:event_txtServiceDescKeyReleased
    //Program to getTableDataToField
    public void getTblData(){
        try{
            int row=tblServiceDesc.getSelectedRow();
            String ServID=tblServiceDesc.getModel().getValueAt(row, 0).toString();
            String sql="Select * from diagnosticsandtests where Service_ID='"+ServID+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txtServiceDesc.setText(rs.getString("Service_Name")+" - "+rs.getString("Service_Description"));
                txtCost.setText(rs.getString("Service_Cost"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    double cost=0,quantity=0,total=0;
    //Program to calculate total
    public void calTot(){
        try{
            cost=Double.parseDouble(txtCost.getText());
            quantity=Double.parseDouble(txtQty.getText());
            total=cost*quantity;
            txtTotal.setText(String.valueOf(total));
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        // TODO add your handling code here:
        if(!"".equals(txtQty.getText()) && !"".equals(txtCost.getText())){
            calTot();
        }
        else{
            txtTotal.setText("0");
        }
    }//GEN-LAST:event_txtQtyKeyReleased
    //Program to add product to database
    public void addProduct(){
        try{
            String sql="insert into opdbillingcontent(opdBillNumber,opdPatID,opdPatName,"
                    + "opdServiceDescription,opdServiceCost,opdServiceQty,"
                    + "opdServiceTotalCost,opdActiveLogin)values(?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1, txtBillNumber.getText());
            pst.setString(2, txtPatientID.getText());
            pst.setString(3, txtPatientName.getText());
            pst.setString(4, txtServiceDesc.getText());
            pst.setString(5, txtCost.getText());
            pst.setString(6, txtQty.getText());
            pst.setString(7, txtTotal.getText());
            pst.setString(8, opdActiveUsername);
            pst.execute();
            pst.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e,"addProduct() Exception",JOptionPane.ERROR_MESSAGE);
        }
    }
    //Program to add data to OPD Billing Table
    public void readBillData(){
        try{
            String sql="Select * from opdbillingcontent where opdBillNumber='"+txtBillNumber.getText()+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblOPDDiagnosticsAndTests.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e,"readBillData() Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void txtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            addProduct();
            totalCalc();
            readBillData();
            clearfield();
        }
    }//GEN-LAST:event_txtQtyKeyPressed
    //Program to load selected table row to respective jtextfields
    public void loadSelect(){
        try{
            txtServiceDesc.setText(tblServiceDesc.getValueAt(0, 1).toString());
            txtCost.setText(tblServiceDesc.getValueAt(0, 2).toString());
            txtQty.requestFocus();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }    
    private void txtServiceDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServiceDescKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            loadSelect();
        }
    }//GEN-LAST:event_txtServiceDescKeyPressed
    //Program to calculate Grand Total on tax keypress
    public void calGTOnTaxEntry(){
        if(!"".equals(txtTax.getText())){
            taxper=Double.parseDouble(txtTax.getText());
            tax=tot*(taxper/100);
            gt=tot+tax;
            txtGrandTotal.setText(String.valueOf(gt));
        }
        else{
            taxper=0;
            tax=tot*(taxper/100);
            gt=tot+tax;
            txtGrandTotal.setText(String.valueOf(gt));
        }        
    }
    private void txtTaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaxKeyReleased
        // TODO add your handling code here:
        calGTOnTaxEntry();
    }//GEN-LAST:event_txtTaxKeyReleased
    //Program to get selected service to field
    String opdServContID;
    public void getTblServiceToField(){
        try{
            int row=tblOPDDiagnosticsAndTests.getSelectedRow();
            opdServContID=tblOPDDiagnosticsAndTests.getModel().getValueAt(row, 0).toString();
            String sql="Select * from opdbillingcontent where opdServiceContentID='"+opdServContID+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txtServiceDesc.setText(rs.getString("opdServiceDescription"));
                txtCost.setText(rs.getString("opdServiceCost"));
                txtQty.setText(rs.getString("opdServiceQty"));
                txtTotal.setText(rs.getString("opdServiceTotalCost"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e,"getTblServiceToField() Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void tblOPDDiagnosticsAndTestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOPDDiagnosticsAndTestsMouseClicked
        // TODO add your handling code here:
        getTblServiceToField();
    }//GEN-LAST:event_tblOPDDiagnosticsAndTestsMouseClicked
    //Program to update added Product List
    public void updtService(){
        try{
            String sql="update opdbillingcontent set opdServiceDescription='"+txtServiceDesc.getText()+"',"
                    + "opdServiceCost='"+txtCost.getText()+"',opdServiceQty='"+txtQty.getText()+"',"
                    + "opdServiceTotalCost='"+txtTotal.getText()+"' where opdServiceContentID='"+opdServContID+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Data Updated Successfully","Data Updated",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e,"updtService() Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(!"".equals(opdServContID)){
            updtService();
        }       
        totalCalc();
        readBillData();
        clearfield();
    }//GEN-LAST:event_btnUpdateActionPerformed
    //Program to delete added service
    public void delProduct(){
        try{
            String sql="Delete from opdbillingcontent where opdServiceContentID='"+opdServContID+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Product removed from billing list","Data Updated",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e,"delProduct() Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(!"".equals(opdServContID)){
            delProduct();
        }
        totalCalc();
        readBillData();
        clearfield();
    }//GEN-LAST:event_btnDeleteActionPerformed
    //Program to save billing
    public void saveBilling(){
        try{
            String sql="insert into opdbilling(bill_no,pat_id,payment_type,payment_desc,overall_total,tax,grand_total,bill_date,bill_time)"
                    + "values(?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1, txtBillNumber.getText());
            pst.setString(2, txtPatientID.getText());
            pst.setString(3, cmbPaymentType.getSelectedItem().toString());
            pst.setString(4, txtPaymentDescription.getText());
            pst.setString(5, txtOverAllTotal.getText());
            pst.setString(6, txtTax.getText());
            pst.setString(7, txtGrandTotal.getText());
            pst.setString(8, dt);
            pst.setString(9, tm);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Billing Details Saved Successfully","Data Saved",JOptionPane.INFORMATION_MESSAGE);
            btnSaveBilling.setEnabled(false);
            btnUpdtBilling.setEnabled(true);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e,"saveBilling() Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnSaveBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBillingActionPerformed
        // TODO add your handling code here:
        saveBilling();
    }//GEN-LAST:event_btnSaveBillingActionPerformed
    //Program to update Billing
    public void updtBilling(){
        try{
            String sql="update opdbilling set payment_type='"+cmbPaymentType.getSelectedItem().toString()+"',payment_desc='"+txtPaymentDescription.getText()+"',"
                    + "overall_total='"+txtOverAllTotal.getText()+"',tax='"+txtTax.getText()+"',grand_total='"+txtGrandTotal.getText()+"',"
                    + "bill_date='"+dt+"',bill_time='"+tm+"' where bill_no='"+txtBillNumber.getText()+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Billing Details Updated Successfully","Data Updated",JOptionPane.INFORMATION_MESSAGE);
            btnSaveBilling.setEnabled(false);
            btnUpdtBilling.setEnabled(true);
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e,"updtBilling() Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnUpdtBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdtBillingActionPerformed
        // TODO add your handling code here:
        updtBilling();
    }//GEN-LAST:event_btnUpdtBillingActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OPDBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OPDBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OPDBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OPDBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OPDBilling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrintBilling;
    private javax.swing.JButton btnSaveBilling;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdtBilling;
    private javax.swing.JComboBox<String> cmbPaymentType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTable tblOPDDiagnosticsAndTests;
    private javax.swing.JTable tblServiceDesc;
    private javax.swing.JTextField txtBillNumber;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtGrandTotal;
    private javax.swing.JTextField txtOverAllTotal;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPaymentDescription;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtServiceDesc;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
